[workspace]
resolver = "2"
members = [ "configuration", "configuration-scraper", "fm-synthesizer-fca", "feature-model-generator-milp", "fm-synthesizer-flat", "cargo-toml", "analysis", "crate-scraper"]
