[workspace]
resolver = "2"
members = ["configuration-scraper", "fm-synthesizer-fca", "feature-model-generator-milp", "fm-synthesizer-flat", "cargo-toml", "analysis", "crate-scraper", "uvl_converter"]
